version: '3.9'
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./ops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./ops/prometheus/rules:/etc/prometheus/rules:ro
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:10.4.2
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./ops/grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./ops/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./ops/grafana/dashboards-files:/var/lib/grafana/dashboards:ro
    ports:
      - "3001:3000"
