global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: nfse-sp-service
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:3000"]
