apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfse-sp-service
  labels:
    app: nfse-sp-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfse-sp-service
  template:
    metadata:
      labels:
        app: nfse-sp-service
    spec:
      containers:
        - name: app
          image: your-registry/nfse-sp-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_ENV
              value: "production"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: nfse-secrets
                  key: jwt_secret
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: nfse-secrets
                  key: database_url
            - name: METRICS_ENABLED
              value: "1"
          ports:
            - name: http
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /live
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: nfse-sp-service
  labels:
    app: nfse-sp-service
spec:
  selector:
    app: nfse-sp-service
  ports:
    - name: http
      port: 80
      targetPort: 3000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nfse-sp-service
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: nfse-sp-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
