name: CI

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: nfse
          POSTGRES_PASSWORD: nfse
          POSTGRES_DB: nfse
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U nfse" --health-interval=10s --health-timeout=5s --health-retries=5
    env:
      DATABASE_URL: postgresql://nfse:nfse@localhost:5432/nfse?schema=public
      JWT_SECRET: test_secret_change_me
      IN_MEMORY_DB: 0
      NODE_ENV: test
      LOG_LEVEL: error
      METRICS_ENABLED: 0
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - name: Install UI dependencies
        run: cd ui && npm ci
      - name: Validate lockfiles are up to date
        run: |
          npm ci --dry-run 2>&1 | grep -q "npm ci can only install" && echo "Root package-lock.json is outdated" && exit 1 || echo "Root lockfile OK"
          cd ui && npm ci --dry-run 2>&1 | grep -q "npm ci can only install" && echo "UI package-lock.json is outdated" && exit 1 || echo "UI lockfile OK"
      - run: npx prisma generate
      - name: Reset database
        run: npx prisma migrate reset --force --skip-generate
      - run: npx prisma migrate deploy
      - run: npm run lint
      - run: npm test -- --ci --runInBand
      - run: npm run build

  docker-image:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Install UI dependencies
        run: cd ui && npm ci
      - name: Validate lockfiles are up to date
        run: |
          npm ci --dry-run 2>&1 | grep -q "npm ci can only install" && echo "Root package-lock.json is outdated" && exit 1 || echo "Root lockfile OK"
          cd ui && npm ci --dry-run 2>&1 | grep -q "npm ci can only install" && echo "UI package-lock.json is outdated" && exit 1 || echo "UI lockfile OK"
      - run: npm run build
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=sha
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |-
            image=moby/buildkit:latest
            network=host
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}